[
    {
      "_id": "68ea96a561fbde3ccb0181f0",
      "userId": "68ea96a561fbde3ccb0181ed",
      "fullName": "Do Nguyen Duc Thanh (K18 HL)",
      "dob": "2004-03-15",
      "gender": "male",
      "ethnicity": "Kinh",
      "nationality": "Vietnam",
      "occupation": "Sinh viên",
      "citizenId": "012345678900",
      "phone": "+84901234567",
      "email": "duc.thanh@example.com",
      "address": "Phường Hòa Bình, Hà Nội",
      "insuranceNumber": "VN1234567890",
      "primaryClinic": "Phòng khám MedConnect Hà Nội",
      "insuranceValidFrom": "2024-01-01",
      "insuranceValidTo": "2026-01-01",
      "bloodType": "A+",
      "allergyNotes": "Cồn",
      "medicalHistory": ["Viêm mũi dị ứng"],
      "vaccinationHistory": [
        { "vaccineName": "Covid-19 Pfizer", "date": "2023-02-10", "place": "Hà Nội" },
        { "vaccineName": "Cúm mùa", "date": "2024-09-15", "place": "Hà Nội" }
      ],
      "emergencyContactName": "Đỗ Văn Thành",
      "emergencyContactPhone": "+84901230000",
      "relationshipToOwner": "self",
      "vneidId": "VNEID12345678",
      "avatarUrl": "/uploads/patient1.png",
      "notes": "Sức khỏe ổn định, không có bệnh mạn tính.",
      "isProfileComplete": true
    },
    {
      "_id": "68eb71c43386dd5747ac5981",
      "userId": "68eb71c43386dd5747ac597f",
      "fullName": "Thanh Bình",
      "dob": "2003-05-10",
      "gender": "male",
      "ethnicity": "Kinh",
      "nationality": "Vietnam",
      "occupation": "Kỹ sư phần mềm",
      "citizenId": "045678901234",
      "phone": "+84962209262",
      "email": "binh.thanh@example.com",
      "address": "Nguyễn Văn Cừ, TP Hồ Chí Minh",
      "insuranceNumber": "VN5566778899",
      "primaryClinic": "Phòng khám MedConnect HCM",
      "insuranceValidFrom": "2023-06-01",
      "insuranceValidTo": "2025-06-01",
      "bloodType": "O+",
      "allergyNotes": "Không có",
      "medicalHistory": ["Cận thị nhẹ"],
      "vaccinationHistory": [
        { "vaccineName": "Viêm gan B", "date": "2021-03-12", "place": "TP.HCM" },
        { "vaccineName": "Covid-19 Moderna", "date": "2022-01-21", "place": "TP.HCM" }
      ],
      "emergencyContactName": "Nguyễn Thị Hoa",
      "emergencyContactPhone": "+84901112233",
      "relationshipToOwner": "self",
      "avatarUrl": "/uploads/patient2.png",
      "notes": "Thường xuyên tập thể dục buổi sáng.",
      "isProfileComplete": true
    },
    {
      "_id": "68eb744d214882d70f0f8671",
      "userId": "68eb744d214882d70f0f866e",
      "fullName": "Ngô Thanh Bình (K18 HL)",
      "dob": "2003-08-25",
      "gender": "male",
      "ethnicity": "Kinh",
      "nationality": "Vietnam",
      "occupation": "Sinh viên",
      "citizenId": "067890123456",
      "phone": "+84961112233",
      "email": "ngothanh.binh@example.com",
      "address": "Hòa Bình, Việt Nam",
      "bloodType": "B+",
      "allergyNotes": "Không có",
      "medicalHistory": ["Viêm họng mãn tính"],
      "vaccinationHistory": [
        { "vaccineName": "Covid-19 AstraZeneca", "date": "2022-03-14", "place": "Hòa Bình" }
      ],
      "emergencyContactName": "Ngô Văn Lợi",
      "emergencyContactPhone": "+84901114567",
      "relationshipToOwner": "self",
      "notes": "Bệnh nhân thường xuyên khám tai mũi họng định kỳ.",
      "isProfileComplete": true
    },
    {
      "_id": "68ebaadbd0ef9c92e5b2b5e6",
      "userId": "68ebaadbd0ef9c92e5b2b5e4",
      "fullName": "Đỗ Nguyễn Đức Minh",
      "dob": "2002-06-20",
      "gender": "male",
      "ethnicity": "Kinh",
      "nationality": "Vietnam",
      "occupation": "Kỹ sư CNTT",
      "citizenId": "012345678901",
      "phone": "+84393501658",
      "email": "minh.nguyen@example.com",
      "address": "123 Nguyễn Văn Cừ, TP Hồ Chí Minh",
      "insuranceNumber": "VN999999999",
      "primaryClinic": "Phòng khám MedConnect HCM",
      "insuranceValidFrom": "2023-10-01",
      "insuranceValidTo": "2025-10-01",
      "bloodType": "B+",
      "allergyNotes": "Không có",
      "medicalHistory": ["Cận thị nhẹ"],
      "vaccinationHistory": [
        { "vaccineName": "Viêm gan B", "date": "2020-03-12", "place": "TP.HCM" },
        { "vaccineName": "Covid-19 Moderna", "date": "2022-01-21", "place": "TP.HCM" }
      ],
      "emergencyContactName": "Nguyễn Thị Hoa",
      "emergencyContactPhone": "+84901112233",
      "relationshipToOwner": "self",
      "notes": "Thường xuyên kiểm tra mắt định kỳ.",
      "isProfileComplete": true
    },
    {
      "_id": "68ecd214246f55aebcd53bcd",
      "userId": "68ecd214246f55aebcd53bcb",
      "fullName": "Nguyễn Khánh",
      "dob": "1998-12-05",
      "gender": "male",
      "ethnicity": "Kinh",
      "nationality": "Vietnam",
      "occupation": "Nhân viên kinh doanh",
      "citizenId": "045612345678",
      "phone": "+84398723124",
      "email": "khanh.nguyen@example.com",
      "address": "Đà Nẵng, Việt Nam",
      "bloodType": "O+",
      "allergyNotes": "Bụi phấn hoa",
      "medicalHistory": ["Viêm mũi dị ứng"],
      "vaccinationHistory": [
        { "vaccineName": "Cúm mùa", "date": "2024-10-10", "place": "Đà Nẵng" }
      ],
      "emergencyContactName": "Nguyễn Thị Mai",
      "emergencyContactPhone": "+84902223344",
      "relationshipToOwner": "self",
      "notes": "Dị ứng nhẹ với phấn hoa mùa xuân.",
      "isProfileComplete": true
    },
    {
      "_id": "68efa5901475ef052ac51a7e",
      "userId": "68efa5901475ef052ac51a7c",
      "fullName": "Lò Văn Tôn",
      "dob": "1995-11-10",
      "gender": "male",
      "ethnicity": "Thái",
      "nationality": "Vietnam",
      "occupation": "Nông dân",
      "citizenId": "079876543210",
      "phone": "+84912312345",
      "email": "ton.lo@example.com",
      "address": "Sơn La, Việt Nam",
      "bloodType": "A-",
      "allergyNotes": "Không có",
      "medicalHistory": ["Đau lưng mãn tính"],
      "vaccinationHistory": [
        { "vaccineName": "Covid-19 AstraZeneca", "date": "2021-09-20", "place": "Sơn La" }
      ],
      "emergencyContactName": "Lò Thị Hoa",
      "emergencyContactPhone": "+84901220000",
      "relationshipToOwner": "self",
      "notes": "Cần nghỉ ngơi định kỳ sau lao động nặng.",
      "isProfileComplete": true
    },
    {
      "_id": "68efae0b2247d69effc0c67b",
      "userId": "68efae0b2247d69effc0c679",
      "fullName": "Khanh123",
      "dob": "2001-02-18",
      "gender": "male",
      "ethnicity": "Kinh",
      "nationality": "Vietnam",
      "occupation": "Sinh viên",
      "citizenId": "045678987654",
      "phone": "+84987654444",
      "email": "khanh123@example.com",
      "address": "Ninh Bình, Việt Nam",
      "bloodType": "B+",
      "allergyNotes": "Không có",
      "medicalHistory": ["Không có bệnh mạn tính"],
      "vaccinationHistory": [
        { "vaccineName": "Covid-19 Pfizer", "date": "2022-10-15", "place": "Ninh Bình" }
      ],
      "emergencyContactName": "Nguyễn Văn Lực",
      "emergencyContactPhone": "+84906543210",
      "relationshipToOwner": "self",
      "notes": "Hồ sơ đầy đủ, sức khỏe tốt.",
      "isProfileComplete": true
    }
  ]
  