FROM node:20-alpine
WORKDIR /app
COPY package.json package-lock.json* pnpm-lock.yaml* yarn.lock* ./ 2>/dev/null || true
RUN npm i
COPY . .
RUN npm run build || true
EXPOSE 4000
CMD ["npm","run","dev"]
